### ISSUE TITLE
Config file is Missing

### ISSUE THREAD

**Issue by AsadSeeker** [Pamblam/Crawler#2]
the file crawler/config.php is missing ... Kindly add it thanks :)

**Comment by Pamblam** [comment]
I was working on updates and got distracted.. the last working version is here: 

https://github.com/Pamblam/Crawler/tree/612baf4eedcb23df3a3e333d6c03855d6922b735

If you want to try and figure out the version on the master branch, the config file is now located in /instances/crawler.ini

You might also consider looking at one of the forks of this repo.
